# https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
#    ignore:
#      # Ignore updates to packages that start with 'aws'
#      # Wildcards match zero or more arbitrary characters
#      - dependency-name: "aws*"
#      # Ignore some updates to the 'express' package
#      - dependency-name: "express"
#        # Ignore only new versions for 4.x and 5.x
#        versions: [ "4.x", "5.x" ]
#      # For all packages, ignore all patch updates
#      - dependency-name: "*"
#        update-types: [ "version-update:semver-patch" ]
